#!/bin/bash

BINDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

for i in "$@" ; do
    if [[ $i == "-c" ]] ; then
        i386-elf-gcc -ffreestanding -mpreferred-stack-boundary=2 "$@" \
            -isystem $BINDIR/../../libc
        exit
    fi
done

i386-elf-gcc -ffreestanding -mpreferred-stack-boundary=2 "$@" \
    -nostdlib \
    -static-libgcc -lgcc \
    -isystem $BINDIR/../../libc \
    -Xlinker $BINDIR/../../libc/stdio.o \
    -Xlinker $BINDIR/../../libc/stdlib.o \
    -Xlinker $BINDIR/../../libc/ctype.o \
    -Xlinker $BINDIR/../../libc/string.o \
    -Xlinker --oformat=binary \
    -T $BINDIR/../../libc/default_linker.ld
