#!/bin/bash

BINDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

for i in "$@" ; do
    if [[ $i == "-c" ]] ; then
        i386-elf-gcc -ffreestanding -mpreferred-stack-boundary=2 "$@" \
            -fdata-sections -ffunction-sections \
            -isystem $BINDIR/../../libc
        exit
    fi
done

OUTPUT_NAME="a.out"
ARGS_STR=""

for ((i=1; i<=$#; i++)); do
    if [[ ${!i} == "-o" ]] ; then
        i=$((i+1))
        OUTPUT_NAME=${!i}
        continue
    fi
    ARGS_STR="$ARGS_STR ${!i}"
done

i386-elf-gcc -ffreestanding -mpreferred-stack-boundary=2 \
    -isystem $BINDIR/../../libc \
    $BINDIR/../../libc/entry.o \
    $BINDIR/../../libc/stdio.o \
    $BINDIR/../../libc/stdlib.o \
    $BINDIR/../../libc/ctype.o \
    $BINDIR/../../libc/string.o \
    $BINDIR/../../libc/unistd.o \
    $ARGS_STR \
    -nostdlib \
    -static-libgcc -lgcc \
    -fdata-sections -ffunction-sections -Wl,--gc-sections \
    -Wl,--entry,_entry \
    -Wl,-r \
    -o .cc-tmp.elf

i386-elf-ld .cc-tmp.elf -o $OUTPUT_NAME --gc-sections \
    -T $BINDIR/../../libc/default_linker.ld \
    --oformat=binary

rm .cc-tmp.elf
