#!/bin/bash

BINDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

i386-elf-gcc -ffreestanding -mpreferred-stack-boundary=2 -nostdlib "$@" \
    -static-libgcc -lgcc \
    -isystem $BINDIR/../../kernel/include/
